version: "3.7"
services:
  taskagile_mysql:
    build:
      context: ./
      dockerfile: ./mysql.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_USER: admin
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_secret
      MYSQL_DATABASE: task_agile
      TZ: Asia/Seoul
    secrets:
      - mysql.secret
    ports:
      - '3306:3306'
    volumes:
      - task_agile_mysql_data:/var/lib/mysql

secrets:
  mysql_secret:
    file: mysql.secret

volumes:
  task_agile_mysql_data:
