---

- name: Install JDK 8
  yum:
    name: java-1.8.0-openjdk-devel
    state: latest
  become: yes

- name: correct java version selected
  alternatives:
    name: java
    path: /usr/lib/jvm/java-1.8.0-openjdk/bin/java
